cask_args appdir: '/Applications'

brew "php@8.1"
brew "php@8.2"
brew "php"
brew "composer"
brew "fnm"
brew "gh"
brew "htop"
brew "telnet"
brew "wakeonlan"
brew "wget"
brew "antigen"
brew "coreutils"
brew "grep"
brew "nmap"
brew "awscli"
brew "qcachegrind"
brew "mas"
brew "redis"
brew "lazydocker"
brew "lazygit"
brew "1password-cli"

cask "docker"
cask "ksdiff"
cask "iterm2"
cask "visual-studio-code"
cask "tower"
cask "notion"
cask "clickup"
cask "spotify"
cask "tableplus"
cask "sublime-text"
cask "microsoft-edge"
cask "firefox"
cask "betterzip"
cask "iina"
cask "shuttle"
cask "tuxera-ntfs"
cask "soundsource"
cask "discord"
cask "tinkerwell"
cask "little-snitch"

mas "Pixelmator Pro", id: 1289583905
mas "Kaleidoscope", id: 587512244
mas "Magnet", id: 441258766
mas "Dato", id: 1470584107
mas "XCode", id: 497799835
mas "Bear", id: 1091189122
mas "Slack", id: 803453959
mas "Gaplin", id: 768053424
# mas "Reeder", id: 1449412482
# mas "Transmit 5", id: 1436522307
mas "ColorSlurp", id: 1287239339