cask_args appdir: '/Applications'

#
# Homebrew
#

# Programming languages
brew "php@8.1"
brew "php@8.2"
brew "php"
brew "composer"
brew "fnm"
brew "jenv"
brew "pyenv"

# Mobile development (Android)
brew "bundletool"
brew "android-platform-tools"

# Terminal tools
brew "sheldon"
brew "starship"

# GNU/Linux stuff
brew "coreutils"
brew "grep"
brew "nmap"
brew "htop"

# IDEs and browsers
cask "visual-studio-code"
cask "sublime-text"
cask "chrome"
cask "microsoft-edge"
cask "firefox"

# Other programming tools
cask "docker"
cask "ksdiff"
cask "iterm2"
cask "tower"
cask "tableplus"
brew "qcachegrind"
brew "lazydocker"
brew "lazygit"

# Day by day tools (essentials)
cask "notion"
cask "clickup"
cask "soundsource"
cask "tuxera-ntfs"
cask "betterzip"
cask "shuttle"
cask "spotify"
cask "iina"
cask "discord"
cask "tinkerwell"
brew "1password-cli"

# Sysadmin stuff
cask "little-snitch"
cask "stats"
brew "gh"
brew "telnet"
brew "wakeonlan"
brew "wget"
brew "awscli"

brew "mas"

#
# App Store
#
mas "Pixelmator Pro", id: 1289583905
mas "Kaleidoscope", id: 587512244
mas "Magnet", id: 441258766
mas "Dato", id: 1470584107
mas "XCode", id: 497799835
mas "Bear", id: 1091189122
mas "Slack", id: 803453959
mas "Gaplin", id: 768053424
# mas "Reeder", id: 1449412482
# mas "Transmit 5", id: 1436522307
mas "ColorSlurp", id: 1287239339